# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "nw0EMd1EvRplviAfhlGFLtihYQBjD5difjpDudK7mGLy5Jw8CfD8Ypmh2UgqM0SBEzTRO2eqHCUfx6mvtZFSQB+KIu2nBVf5rvT5T0VrV6U+zMMyCwn6jWBT9/LnF6Z21VFEX52YwFDeKzUTnju+atwMvJtqBOz1XPj5elmPLbXxYp9c6rOLz2BZPPw5fKR1NF55KHc8C7HxoBFyzBt/leNJRHTlR0mH9DSGt3T+4075THqxv129b/OGJH+Nb+ajunfIJkgHwwSf0F3EbCbf19faaEa5jorlQFkmA1lZC3PHvtnld04fYs+Hmv/isKX6Poj6FxgKBhuq0DgYdjTHx9jqeMKEx40WzTJEmKANQyBPh5KjjdUkbVJB38eTljrMWBq5euyFFM4rUvG5yknfxGT9/Q99J/2FDuEjMp4NwZyr9IeBjh81/BBmZu5/JZdSmJrTxSMj8vUb6DQDXIpNETAtglDpvfWTcFRaQNNpwm7QGFs2K5vBbzD4w+E/+6eo/If4/N+hbvCpDohgBDsM02B/54BvDidFfJOFbDwPM5t7fnzkGyTdYCn098CH+L6h/12rsPCGbVMm+OueA/ajr6X7HNJ8w3aDTpVMmTvW9aPNmcG7OmLxd080tvTcgsdyHga8DyueTfdmjngj5LZStZeru3SQDUMsPiu0futKrac="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
