travis:
  secure:
    BINSTAR_TOKEN: nw0EMd1EvRplviAfhlGFLtihYQBjD5difjpDudK7mGLy5Jw8CfD8Ypmh2UgqM0SBEzTRO2eqHCUfx6mvtZFSQB+KIu2nBVf5rvT5T0VrV6U+zMMyCwn6jWBT9/LnF6Z21VFEX52YwFDeKzUTnju+atwMvJtqBOz1XPj5elmPLbXxYp9c6rOLz2BZPPw5fKR1NF55KHc8C7HxoBFyzBt/leNJRHTlR0mH9DSGt3T+4075THqxv129b/OGJH+Nb+ajunfIJkgHwwSf0F3EbCbf19faaEa5jorlQFkmA1lZC3PHvtnld04fYs+Hmv/isKX6Poj6FxgKBhuq0DgYdjTHx9jqeMKEx40WzTJEmKANQyBPh5KjjdUkbVJB38eTljrMWBq5euyFFM4rUvG5yknfxGT9/Q99J/2FDuEjMp4NwZyr9IeBjh81/BBmZu5/JZdSmJrTxSMj8vUb6DQDXIpNETAtglDpvfWTcFRaQNNpwm7QGFs2K5vBbzD4w+E/+6eo/If4/N+hbvCpDohgBDsM02B/54BvDidFfJOFbDwPM5t7fnzkGyTdYCn098CH+L6h/12rsPCGbVMm+OueA/ajr6X7HNJ8w3aDTpVMmTvW9aPNmcG7OmLxd080tvTcgsdyHga8DyueTfdmjngj5LZStZeru3SQDUMsPiu0futKrac=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
