travis:
  secure:
    BINSTAR_TOKEN: osoUpoVwmCOhiNCRxLcq4Q2dQtGf2sTJds/VVPQVkvhle4CayNOTXaTgTcoh5Mq/kimn0lhjz9Dyh9Fggpb+SCQ6ODbqqIwfXi5zS9dsl83KEwEJhJesYHpzIDP7j6mRjTkKgPjyJUcQb0B52hGHhHKiHKDdGlPMH/CPt2Y8WxrhgQbEhmjGq79endKq671bevdRtKYB6V1mFFPKDmkSW82ij22HLC7AeS9RUtutS6ulvBrgfpxc1H6kb/HjOKf97e4zriuScmoz6lpqn8URZnj04wCNJOsyac6Kt4Dj5pabTOAJg79O1Ffc77T44Ad54TC4j5/3/HpmifeByGP4sneIwfPrL0wqpQCOoemAA6gEKAO1iEjwhgIYED8eeQfOm4cwxsLaTp6o91CSymBhUgppITAOC9X7GTyw6ls4eV+G8KVmb8DZZASAs5ll9fUdtXOdSK2BIjSo/iLPnUjXSVr3R2CNTiC3mYIV4XI4wXqfKjD41HS87tM/p7Srf+5xv1icykOWAlyekECDNTHAHJKZ/jfr3nTwZyjQUPAMxEIB3I3S6CUg/CdJjgQ8gHjtNfQgulLH0YgiCtENIJFqMxCTa3fNzjEHUc2c6g4dW/OwIC4/zFCDgY7WDgD+kOCf84GX3307bzQswh9WmGbvgQmga4GVM5lM5B6vvck+9tk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
